In [74]:
import pandas as pd
import os

# From World Mining Data 2024

In [75]:
file_path_wmd = 'data/World_mining_data_2024/6.5. Share_of_World_Mineral_Production_2022_by_Countries.xlsx'

In [76]:
def get_canada_production_data_wmd(file_path):
    """
    Reads an Excel file with multiple sheets, each representing a commodity.
    Extracts Canada's production, world share, and unit for each commodity, returning a DataFrame.
    Commodities are listed in alphabetical order, with 0s for missing data.
    
    Parameters:
    - file_path (str): Path to the Excel file containing the data.
    
    Returns:
    - pd.DataFrame: DataFrame with columns: ['Commodity', 'Production Volume', 'World Share (%)', 'Unit']
    """
    # Load the Excel file
    excel_data = pd.ExcelFile(file_path)
    
    # Initialize a dictionary to store production volume, world share data, and units for Canada
    canada_production_data = {'Commodity': [], 'Production Volume': [], 'World Share (%)': [], 'Unit': []}
    
    # Loop through each sheet, extract Canada's data if present
    for sheet in excel_data.sheet_names:
        df = excel_data.parse(sheet, skiprows=1)  # Start reading from the second row with corrected column headers
        canada_row = df[df['Country'].str.contains("Canada", na=False)]
        
        # Get the unit if present, default to 'tonnes' if not specified
        unit = df['unit'].iloc[0] if 'unit' in df.columns else 'tonnes'
        
        # Add data or fill with 0 if Canada data is missing
        canada_production_data['Commodity'].append(sheet)
        canada_production_data['Unit'].append(unit)
        if not canada_row.empty:
            canada_production_data['Production Volume'].append(float(canada_row['Production 2022'].values[0]))
            canada_production_data['World Share (%)'].append(float(canada_row['Share in %'].values[0]))
        else:
            canada_production_data['Production Volume'].append(0)
            canada_production_data['World Share (%)'].append(0)

    # Convert the dictionary to a DataFrame and sort alphabetically by Commodity
    canada_production_df = pd.DataFrame(canada_production_data).sort_values(by="Commodity").reset_index(drop=True)
    
    return canada_production_df

In [77]:
# We keep only non 0 production volume
canada_production_df = get_canada_production_data_wmd(file_path_wmd)
canada_production_df = canada_production_df[canada_production_df['Production Volume'] != 0]
canada_production_df

,Commodity,Production Volume,World Share (%),Unit
0,Aluminium,3033966.0,4.408193,metr. t
1,Antimony,2.0,0.002409,metr. t
4,Baryte,50000.0,0.603986,metr. t
10,Cadmium,1800.0,7.825066,metr. t
12,Cobalt,3063.0,1.844847,metr. t
13,Coking Coal,26461240.0,2.539750,metr. t
14,Copper,510782.0,2.298189,metr. t
15,Diamonds (Gem),17728144.0,22.325758,ct
19,Fluorspar,20000.0,0.216534,metr. t
22,Gold,205831.0,6.193863,kg
23,Graphite,13000.0,0.752539,metr. t
24,Gypsum and Anhydrite,3174070.0,1.793377,metr. t
25,Indium,39.0,3.869048,metr. t
26,Iron (Fe),42073900.0,2.718035,metr. t
28,Lead,8247.0,0.175694,metr. t
29,Lignite,6427680.0,0.897231,metr. t
31,Magnesite,230000.0,0.861561,metr. t
34,Molybdenum,1146.0,0.431703,metr. t
35,Natural Gas,186121.0,4.475801,Mio m3
36,Nickel,143266.0,4.409683,metr. t
37,Niobium (Nb2O5),6800.0,5.752523,metr. t
38,Oil Sands (part of Petroleum),179386500.0,90.880835,metr. t
40,Palladium,16099.0,7.969329,kg
42,Petroleum,271233300.0,6.122785,metr. t
44,Platinum,5490.0,2.999639,kg
45,Potash (K2O),15116101.0,36.027157,metr. t
48,Rhodium,500.0,2.199639,kg
49,"Salt (rock, brines, marine)",14640779.0,5.384908,metr. t
50,Selenium,110.0,2.945114,metr. t
51,Silver,334480.0,1.258184,kg
52,Steam Coal,12201040.0,0.184292,metr. t
53,Sulfur (elementar & industrial),4898600.0,5.918407,metr. t
54,"Talc, Steatite & Pyrophyllite",200000.0,2.563910,metr. t
56,Tellurium,24.0,3.524229,metr. t
58,Titanium (TiO2),540000.0,6.038246,metr. t
60,Uranium (U3O8),6168.0,11.019796,metr. t
63,Zinc,208147.0,1.630981,metr. t

In [78]:
canada_production_df.to_csv(r'data/World_mining_data_2024/canada_production_wmd2024.csv', index=False)

In [79]:
# We drop the FF and those for which we haven't found LCI 
commodities_to_drop = ['Baryte', 'Coking Coal', 'Diamonds (Gem)', 'Gypsum and Anhydrite', 'Lignite', 
                       'Magnesite', 'Natural Gas', 'Oil Sands (part of Petroleum)', 'Petroleum',
                       'Salt (rock, brines, marine)', 'Steam Coal ', 'Sulfur (elementar & industrial)', 
                       'Talc, Steatite & Pyrophyllite']
canada_production_df = canada_production_df[~canada_production_df['Commodity'].isin(commodities_to_drop)]

In [80]:
canada_production_df

          Commodity  Production Volume  World Share (%)     Unit
0         Aluminium          3033966.0         4.408193  metr. t
1          Antimony                2.0         0.002409  metr. t
10          Cadmium             1800.0         7.825066  metr. t
12           Cobalt             3063.0         1.844847  metr. t
14           Copper           510782.0         2.298189  metr. t
19        Fluorspar            20000.0         0.216534  metr. t
22             Gold           205831.0         6.193863       kg
23         Graphite            13000.0         0.752539  metr. t
25           Indium               39.0         3.869048  metr. t
26        Iron (Fe)         42073900.0         2.718035  metr. t
28             Lead             8247.0         0.175694  metr. t
34       Molybdenum             1146.0         0.431703  metr. t
36           Nickel           143266.0         4.409683  metr. t
37  Niobium (Nb2O5)             6800.0         5.752523  metr. t
40        Palladium            16099.0         7.969329       kg
44         Platinum             5490.0         2.999639       kg
45     Potash (K2O)         15116101.0        36.027157  metr. t
48          Rhodium              500.0         2.199639       kg
50         Selenium              110.0         2.945114  metr. t
51           Silver           334480.0         1.258184       kg
56        Tellurium               24.0         3.524229  metr. t
58  Titanium (TiO2)           540000.0         6.038246  metr. t
60   Uranium (U3O8)             6168.0        11.019796  metr. t
63             Zinc           208147.0         1.630981  metr. t

In [81]:
# We put everything in kg
canada_production_df_kg = canada_production_df.copy()
canada_production_df_kg.loc[canada_production_df_kg['Unit'] == 'metr. t', 'Production Volume'] *= 1000
canada_production_df_kg.loc[canada_production_df_kg['Unit'] == 'metr. t', 'Unit'] = 'kg'
canada_production_df_kg.rename(columns={'Production Volume': 'Production Volume (kg)'}, inplace=True)
canada_production_df_kg.drop(columns=['Unit'], inplace=True)
canada_production_df_kg

          Commodity  Production Volume (kg)  World Share (%)
0         Aluminium            3.033966e+09         4.408193
1          Antimony            2.000000e+03         0.002409
10          Cadmium            1.800000e+06         7.825066
12           Cobalt            3.063000e+06         1.844847
14           Copper            5.107820e+08         2.298189
19        Fluorspar            2.000000e+07         0.216534
22             Gold            2.058310e+05         6.193863
23         Graphite            1.300000e+07         0.752539
25           Indium            3.900000e+04         3.869048
26        Iron (Fe)            4.207390e+10         2.718035
28             Lead            8.247000e+06         0.175694
34       Molybdenum            1.146000e+06         0.431703
36           Nickel            1.432660e+08         4.409683
37  Niobium (Nb2O5)            6.800000e+06         5.752523
40        Palladium            1.609900e+04         7.969329
44         Platinum            5.490000e+03         2.999639
45     Potash (K2O)            1.511610e+10        36.027157
48          Rhodium            5.000000e+02         2.199639
50         Selenium            1.100000e+05         2.945114
51           Silver            3.344800e+05         1.258184
56        Tellurium            2.400000e+04         3.524229
58  Titanium (TiO2)            5.400000e+08         6.038246
60   Uranium (U3O8)            6.168000e+06        11.019796
63             Zinc            2.081470e+08         1.630981

In [82]:
canada_production_df_kg.to_csv(r'data/World_mining_data_2024/canada_production_wmd2024_kg.csv', index=False)

## From USGS's Mining Commodities Summary 2024

In [68]:
def get_canada_production_mcs_usgs(folder_path, delimiter=","):
    """
    Parse all CSV (or similarly formatted) files in `folder_path`.
    Keep the first 5 columns: [Source, Country, Type, Prod_2022, Prod_est_2023].

    1. Check if the file has any 'Canada' entry in 'Country' (case-insensitive).
    2. Only if it does, include rows where 'Country' has 'Canada' or 'World'.
    3. Skip the entire file otherwise.
    4. Add a 'FileName' column indicating which CSV file the row came from.
    5. Add a 'Unit' column that stores the original 4th column name (e.g., "Prod_t_2022").

    Returns a single DataFrame with these rows from all files combined.

    Parameters:
    -----------
    folder_path : str
        Path to the folder containing .csv files.
    delimiter : str
        The delimiter for the CSV files (default ',').
        Change to ';' or '\\t' if your file is delimited differently.
    """

    all_data = []

    for filename in os.listdir(folder_path):
        # Only process .csv files
        if filename.lower().endswith(".csv"):
            file_path = os.path.join(folder_path, filename)
            
            # Read the CSV (adjust header or skiprows if your files have extra lines)
            df = pd.read_csv(file_path, delimiter=delimiter, header=0)

            # Make sure there are at least 5 columns
            if df.shape[1] < 5:
                continue

            # Slice the first 5 columns
            subset_df = df.iloc[:, :5].copy()

            # Capture the original name of the 4th column (index=3 in 0-based Python)
            original_4th_col_name = df.columns[3]

            # Rename them to a standard set
            subset_df.columns = [
                "Source",
                "Country",
                "Type",
                "Prod_2022",
                "Prod_est_2023"
            ]

            # Check if the file has any row with 'Canada'
            mask_canada = subset_df["Country"].str.contains("Canada", case=False, na=False)
            if not mask_canada.any():
                # If there's no Canada, skip the entire file
                continue

            # Filter for rows where 'Country' is Canada or World
            mask_final = subset_df["Country"].str.contains("Canada|World", case=False, na=False)
            subset_df = subset_df[mask_final]

            # Add the file name column
            subset_df["FileName"] = filename

            # Add a "Unit" column containing the original 4th column name
            subset_df["Unit"] = original_4th_col_name

            # If there's data left, add to our list
            if not subset_df.empty:
                all_data.append(subset_df)

    # Combine all filtered data
    if all_data:
        final_df = pd.concat(all_data, ignore_index=True)
    else:
        # Return an empty DataFrame with expected columns
        final_df = pd.DataFrame(columns=[
            "Source",
            "Country",
            "Type",
            "Prod_2022",
            "Prod_est_2023",
            "FileName",
            "Unit"
        ])

    return final_df

In [69]:
usgs_mcs_2024 = 'data/USGS/Mineral_commodities_2024'

In [70]:
canada_mcs24_df = get_canada_production_mcs_usgs(usgs_mcs_2024)

In [71]:
canada_mcs24_df

,Source,Country,Type,Prod_2022,Prod_est_2023,FileName,Unit
0,MCS2024,United States and Canada,"Plant capacity, fused aluminum oxide",60000,60000,mcs2024-abras_world.csv,Cap_t_est_2022
1,MCS2024,World total (rounded),"Plant capacity, fused aluminum oxide",1310000,1300000,mcs2024-abras_world.csv,Cap_t_est_2022
2,MCS2024,United States and Canada,"Plant capacity, silicon carbide",0,0,mcs2024-abras_world.csv,Cap_t_est_2022
3,MCS2024,World total (rounded),"Plant capacity, silicon carbide",1000000,1000000,mcs2024-abras_world.csv,Cap_t_est_2022
4,MCS 2024,Canada,"Smelter production, aluminum",2770.0,3000.0,mcs2024-alumi_world.csv,Prod_kt_2022
...,...,...,...,...,...,...,...
89,MCS2024,"World total (ilmenite and rutile, rounded)",World total mine production: ilmentite and rut...,9400,9200,mcs2024-timin_world.csv,Prod_kt_est_2022
90,MCS2024,Canada,Sponge Metal Production and Sponge and Pigment...,0,0,mcs2024-titan_world.csv,Prod_Sponge_t_Est_2022
91,MCS2024,World total (rounded),Sponge Metal Production and Sponge and Pigment...,270000,330000,mcs2024-titan_world.csv,Prod_Sponge_t_Est_2022
92,MCS2024,Canada,"Mine production, wollastonite",20000,20000,mcs2024-wolla_world.csv,Prod_t_est_2022
93,MCS2024,World total (rounded),"Mine production, wollastonite",1120000,1100000,mcs2024-wolla_world.csv,Prod_t_est_2022

In [72]:
canada_mcs24_df.to_csv(r'data/USGS/data_usgs_mineral_commodities_24_processed.csv', index=False)